@startuml UC02_動画閲覧
title UC02_動画閲覧

'Direction of diagram flow can be selected.
left to right direction


actor User
boundary 動画閲覧画面
control 動画取得
entity Video


User -> 動画閲覧画面 : アクセス
動画閲覧画面 -> 動画取得 : 呼び出し
動画取得 -> Video : 問い合わせ

@enduml