@startuml
left to right direction
actor Drone
actor User
usecase UC01動画の送信
usecase UC02動画の閲覧
usecase UC03ドローンの遠隔操縦
usecase UC04クライアントからの命令受信

Drone --> UC01動画の送信
User --> UC02動画の閲覧
User --> UC03ドローンの遠隔操縦
Drone --> UC04クライアントからの命令受信

@enduml
